sampling         5000

[BAT-SOC-CPUFREQ]
algo_type        monitor
sensor           soc
sampling         5000
thresholds       100
thresholds_clr   99
actions          cpu
action_info      1228800

[BAT-SOC-GPU]
algo_type        monitor
sensor           soc
sampling         5000
thresholds       100
thresholds_clr   99
actions          gpu
action_info      520000000
